"""
Embed subsampled landmark cycles from references/calibration/*/frames.csv
into src/engine/calibrationGhostCycles.generated.ts for live WebView ghost.

Run after updating reference CSVs:
  python3 tools/embed_calibration_ghost_cycles.py
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REF_DIRS = [
    ("leftSls", ROOT / "references/calibration/01_left_sls/frames.csv"),
    ("rightSls", ROOT / "references/calibration/02_right_sls/frames.csv"),
    ("leftLsd", ROOT / "references/calibration/03_left_lsd/frames.csv"),
    ("rightLsd", ROOT / "references/calibration/04_right_lsd/frames.csv"),
]
OUT = ROOT / "src/engine/calibrationGhostCycles.generated.ts"

TARGET_FRAMES = 90  # ~3s loop at 30fps — light enough for a bundled string in HTML


def _read_frames(path: Path) -> list[list[dict[str, float]]]:
    rows: list[list[dict[str, float]]] = []
    with path.open(newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for row in r:
            lm: list[dict[str, float]] = []
            for i in range(33):
                try:
                    lm.append(
                        {
                            "x": float(row.get(f"lm{i}_x") or 0),
                            "y": float(row.get(f"lm{i}_y") or 0),
                            "z": float(row.get(f"lm{i}_z") or 0),
                            "v": float(row.get(f"lm{i}_v") or 0),
                        }
                    )
                except ValueError:
                    lm.append({"x": 0.5, "y": 0.5, "z": 0.0, "v": 0.0})
            rows.append(lm)
    return rows


def _subsample(frames: list[list[dict[str, float]]], n: int) -> list[list[dict[str, float]]]:
    if not frames:
        return []
    if len(frames) <= n:
        return frames
    out: list[list[dict[str, float]]] = []
    last = len(frames) - 1
    for j in range(n):
        # cosine spacing — more samples near endpoints (stand / bottom)
        u = (1.0 - math.cos((j / max(1, n - 1)) * math.pi)) / 2.0
        idx = int(round(u * last))
        idx = max(0, min(last, idx))
        out.append(frames[idx])
    return out


def _emit_ts(cycles: dict[str, list[list[dict[str, float]]]]) -> str:
    lines: list[str] = []
    lines.append("/** Auto-generated by tools/embed_calibration_ghost_cycles.py — do not edit. */")
    lines.append("")
    lines.append("export type GhostLandmark = { x: number; y: number; z: number; v: number };")
    lines.append("")
    for key in ("leftSls", "rightSls", "leftLsd", "rightLsd"):
        frames = cycles.get(key, [])
        lines.append(f"export const GHOST_CYCLE_{key.upper()}: GhostLandmark[][] = [")
        for fr in frames:
            parts: list[str] = []
            for lm in fr:
                parts.append(
                    "{"
                    f"x:{lm['x']:.6f},y:{lm['y']:.6f},z:{lm['z']:.6f},v:{lm['v']:.6f}"
                    "}"
                )
            lines.append("  [" + ",".join(parts) + "],")
        lines.append("];")
        lines.append("")
    lines.append("export const GHOST_CYCLE_BY_EXERCISE: Record<string, GhostLandmark[][]> = {")
    lines.append("  leftSls: GHOST_CYCLE_LEFTSLS,")
    lines.append("  rightSls: GHOST_CYCLE_RIGHTSLS,")
    lines.append("  leftLsd: GHOST_CYCLE_LEFTLSD,")
    lines.append("  rightLsd: GHOST_CYCLE_RIGHTLSD,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    cycles: dict[str, list[list[dict[str, float]]]] = {}
    for key, path in REF_DIRS:
        if not path.is_file():
            raise SystemExit(f"Missing reference CSV: {path}")
        raw = _read_frames(path)
        cycles[key] = _subsample(raw, TARGET_FRAMES)
        print(f"{key}: {len(raw)} → {len(cycles[key])} frames from {path}", flush=True)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(_emit_ts(cycles), encoding="utf-8")
    print(f"Wrote {OUT}", flush=True)


if __name__ == "__main__":
    main()
